In [91]:
import numpy as np
import pandas as pd

In [92]:
df = pd.read_csv(r"C:\Users\Ibhrahim ansari\Desktop\self projects\Amazon Sale Report.csv\Amazon Sale Report.csv", low_memory=False)

In [93]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [95]:
df.shape

(128975, 24)

In [96]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [97]:
df.isna().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [98]:
df.isna().sum() / len(df) * 100

index                  0.000000
Order ID               0.000000
Date                   0.000000
Status                 0.000000
Fulfilment             0.000000
Sales Channel          0.000000
ship-service-level     0.000000
Style                  0.000000
SKU                    0.000000
Category               0.000000
Size                   0.000000
ASIN                   0.000000
Courier Status         5.328164
Qty                    0.000000
currency               6.043807
Amount                 6.043807
ship-city              0.025586
ship-state             0.025586
ship-postal-code       0.025586
ship-country           0.025586
promotion-ids         38.110487
B2B                    0.000000
fulfilled-by          69.546811
Unnamed: 22           38.030626
dtype: float64

In [99]:
df.duplicated().sum()

np.int64(0)

In [100]:
df.columns = df.columns.str.strip()
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [101]:
df.drop(columns=["index","Unnamed: 22", "promotion-ids", "fulfilled-by",], inplace = True)

In [102]:
df.columns = df.columns.str.capitalize()

In [103]:
df.columns

Index(['Order id', 'Date', 'Status', 'Fulfilment', 'Sales channel',
       'Ship-service-level', 'Style', 'Sku', 'Category', 'Size', 'Asin',
       'Courier status', 'Qty', 'Currency', 'Amount', 'Ship-city',
       'Ship-state', 'Ship-postal-code', 'Ship-country', 'B2b'],
      dtype='object')

In [104]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst = True)

C:\Users\Ibhrahim ansari\AppData\Local\Temp\ipykernel_580\3245914792.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"], dayfirst = True)

In [105]:
df["Date"]

0        2022-04-30
1        2022-04-30
2        2022-04-30
3        2022-04-30
4        2022-04-30
            ...
128970   2022-05-31
128971   2022-05-31
128972   2022-05-31
128973   2022-05-31
128974   2022-05-31
Name: Date, Length: 128975, dtype: datetime64[ns]

In [106]:
df['Ship-postal-code'] = df['Ship-postal-code'].astype(str)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order id            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales channel       128975 non-null  object
 5   Ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Sku                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  Asin                128975 non-null  object
 11  Courier status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  Currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  Ship-city           128942 non-null  object
 16  Ship-state          128942 non-null  object
 17  Ship-postal-code    128975 non-null  object
 18  Ship-country        128942 non-null  object
 19  B2b                 128975 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(16)
memory usage: 18.8+ MB

In [108]:
df.isna().sum() / len(df) * 100

Order id              0.000000
Date                  0.000000
Status                0.000000
Fulfilment            0.000000
Sales channel         0.000000
Ship-service-level    0.000000
Style                 0.000000
Sku                   0.000000
Category              0.000000
Size                  0.000000
Asin                  0.000000
Courier status        5.328164
Qty                   0.000000
Currency              6.043807
Amount                6.043807
Ship-city             0.025586
Ship-state            0.025586
Ship-postal-code      0.000000
Ship-country          0.025586
B2b                   0.000000
dtype: float64

In [109]:
df["Courier status"].unique()

array([nan, 'Shipped', 'Cancelled', 'Unshipped'], dtype=object)

In [110]:
df['Courier status'] = df['Courier status'].fillna("unknown")
df["Ship-postal-code"] = df["Ship-postal-code"].fillna("unknown")

In [111]:
df["Currency"].unique()

array(['INR', nan], dtype=object)

In [112]:
df["Currency"] = df["Currency"].fillna("INR")

In [113]:
df["Ship-city"] = df["Ship-city"].fillna("unknown")

In [114]:
df["Ship-state"] = df["Ship-state"].fillna("unknown")

In [115]:
df["Ship-country"] = df["Ship-country"].fillna("IN")

In [116]:
df[df['Amount'].isnull()]['Courier status'].value_counts()

Courier status
Cancelled    5935
unknown      1736
Unshipped     124
Name: count, dtype: int64

In [117]:
print(df['Amount'].isnull().sum())

print(df.shape)

print(df.columns.tolist())

7795
(128975, 20)
['Order id', 'Date', 'Status', 'Fulfilment', 'Sales channel', 'Ship-service-level', 'Style', 'Sku', 'Category', 'Size', 'Asin', 'Courier status', 'Qty', 'Currency', 'Amount', 'Ship-city', 'Ship-state', 'Ship-postal-code', 'Ship-country', 'B2b']

In [118]:
df[df['Amount'].isnull()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [119]:
df[df['Amount'].isnull()].head(10)

,Order id,Date,Status,Fulfilment,Sales channel,Ship-service-level,Style,Sku,Category,Size,Asin,Courier status,Qty,Currency,Amount,Ship-city,Ship-state,Ship-postal-code,Ship-country,B2b
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,B08L91ZZXN,Cancelled,0,INR,NaN,HYDERABAD,TELANGANA,500008.0,IN,False
29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,B07JG3CND8,unknown,0,INR,NaN,GUWAHATI,ASSAM,781003.0,IN,False
65,171-4137548-0481151,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,B082W8RWN1,Cancelled,0,INR,NaN,Dahod,Gujarat,389151.0,IN,False
84,403-9950518-0349133,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,B08WPR5MCB,Cancelled,0,INR,NaN,HYDERABAD,TELANGANA,500072.0,IN,False
95,405-9112089-3379536,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,B081WSCKPQ,Cancelled,0,INR,NaN,PUNE,MAHARASHTRA,411046.0,IN,False
101,402-7841951-1872363,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET347,SET347-KR-NP-S,Set,S,B09RKDJ9SQ,Cancelled,0,INR,NaN,NEW DELHI,DELHI,110036.0,IN,False
132,171-0293372-4913973,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET269,SET269-KR-NP-XXXL,Set,3XL,B0983FSRFS,Cancelled,0,INR,NaN,KOLAR,KARNATAKA,563101.0,IN,False
139,403-6442534-2769112,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,J0300,J0300-TP-XXXL,Top,3XL,B099S7RDLZ,Cancelled,0,INR,NaN,AZAMGARH,UTTAR PRADESH,276302.0,IN,False
155,402-8078642-8565124,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3887,JNE3887-KR-XL,kurta,XL,B09TZVXQ1J,Cancelled,0,INR,NaN,Puri-2,ODISHA,752002.0,IN,False
165,406-0218328-1773963,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,PJNE2100,PJNE2100-KR-N-6XL,kurta,6XL,B09LD3PMBT,Cancelled,0,INR,NaN,WALAJAPET,TAMIL NADU,632513.0,IN,False

In [120]:
df.isna().sum()

Order id                 0
Date                     0
Status                   0
Fulfilment               0
Sales channel            0
Ship-service-level       0
Style                    0
Sku                      0
Category                 0
Size                     0
Asin                     0
Courier status           0
Qty                      0
Currency                 0
Amount                7795
Ship-city                0
Ship-state               0
Ship-postal-code         0
Ship-country             0
B2b                      0
dtype: int64

In [121]:
df["Ship-state"].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi',
       'unknown', 'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [122]:
df["Ship-state"] = df["Ship-state"].str.upper()

In [123]:
df["Ship-state"].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'GUJARAT', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'GOA', 'MEGHALAYA', 'TRIPURA',
       'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'UNKNOWN',
       'ANDAMAN & NICOBAR ', 'RAJSHTHAN', 'NL', 'MIZORAM', 'NEW DELHI',
       'PUNJAB/MOHALI/ZIRAKPUR', 'RJ', 'ORISSA', 'LAKSHADWEEP', 'PB',
       'APO', 'AR', 'PONDICHERRY', 'RAJSTHAN'], dtype=object)

In [124]:
state_mapping = {
    "RAJSHTHAN": "RAJASTHAN",
    "RAJSTHAN": "RAJASTHAN",
    "RJ": "RAJASTHAN",
    "ORISSA": "ODISHA",
    "PONDICHERRY": "PUDUCHERRY",
    "NEW DELHI": "DELHI",
    "PB": "PUNJAB",
    "NL": "NAGALAND",
    "AR": "ARUNACHAL PRADESH",
    "PUNJAB/MOHALI/ZIRAKPUR": "PUNJAB",
    "APO": "UNKNOWN",
    "ANDAMAN & NICOBAR ": "ANDAMAN AND NICOBAR ISLANDS"
}

df["Ship-state"] = df["Ship-state"].replace(state_mapping)

In [125]:
df["Ship-state"].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'GUJARAT', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'GOA', 'MEGHALAYA', 'TRIPURA',
       'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'UNKNOWN',
       'ANDAMAN AND NICOBAR ISLANDS', 'MIZORAM', 'LAKSHADWEEP'],
      dtype=object)

In [126]:
sorted(df["Ship-state"].unique())

['ANDAMAN AND NICOBAR ISLANDS',
 'ANDHRA PRADESH',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'DADRA AND NAGAR',
 'DELHI',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LADAKH',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'ODISHA',
 'PUDUCHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'SIKKIM',
 'TAMIL NADU',
 'TELANGANA',
 'TRIPURA',
 'UNKNOWN',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

In [127]:
df["Ship-city"].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ...,
       'GULABPURA, Distt BHILWARA', 'Prayagraj (ALLAHABAD)', 'Halol'],
      shape=(8956,), dtype=object)

In [128]:
df["Ship-city"] = df["Ship-city"].str.upper()

In [129]:
df["Ship-city"] = df["Ship-city"].str.strip()

In [130]:
df["Ship-city"].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ..., 'CHERUKUNNU (P.O)',
       'GULABPURA, DISTT BHILWARA', 'PRAYAGRAJ (ALLAHABAD)'],
      shape=(7298,), dtype=object)

In [131]:
df.isna().sum()

Order id                 0
Date                     0
Status                   0
Fulfilment               0
Sales channel            0
Ship-service-level       0
Style                    0
Sku                      0
Category                 0
Size                     0
Asin                     0
Courier status           0
Qty                      0
Currency                 0
Amount                7795
Ship-city                0
Ship-state               0
Ship-postal-code         0
Ship-country             0
B2b                      0
dtype: int64

In [132]:
df.shape

(128975, 20)

In [135]:
df.to_csv("1_Amazon_Cleaned.csv", index=False)

In [136]:
df["Ship-postal-code"].isna().sum()

np.int64(0)